[workspace]
resolver = "2"
members = [
    # The main framework library
    "justact-core",

    # Derive libs
    "justact-datalog",
    "derive/justact-datalog-derive",
]


[workspace.package]
edition = "2021"
repository = "https://github.com/Lut99/just-act"
