[workspace]
resolver = "2"
members = [
    # Libraries that concretize it
    "justact-datalog",

    # The main framework library
    "justact-core",
]


[workspace.package]
edition = "2021"
repository = "https://github.com/Lut99/just-act"
