[package]
name = "justact-core"
version = "1.0.0"
edition.workspace = true
authors = ["Tim Müller"]
repository.workspace = true
description = "Implements the core framework part of the JustAct framework. For more details, see the paper: "


[dependencies]
nohash-hasher = "0.2"
